server:
  port: 8082
hm:
  db:
    database: hm-cart
    port: 3307
  swagger:
    title: 购物车服务接口文档
    package: com.hmall.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090  #k
      http-method-specify: true # 开启请求方式前缀
feign:
  sentinel:
    enabled: true # 开启feign对sentinel的支持